name: Pull request
description: Template for contributing to Forever Engine Legacy
labels:
body:
  - type: markdown
    attributes:
      value: "Please check for duplicate/similar Pull requests before creating yours."

  - type: dropdown
    attributes:
      label: "Does this Pull request go under the bug or enhancement label?"
      multiple: false
      options:
        - "Bug label"
        - "Enhancement label"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Does this Pull request close any issue(s)? If so, link them below.
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Briefly describe the changes."
    validations:
      required: true
